In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(list(uploaded.keys())[0])

Saving shopping_trends.csv to shopping_trends.csv

In [3]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.shape

(3900, 19)

In [6]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Payment Method',
       'Shipping Type', 'Discount Applied', 'Promo Code Used',
       'Previous Purchases', 'Preferred Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [7]:
df.dtypes

Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

In [9]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["Customer ID"].nunique()

3900

In [12]:
import matplotlib.pyplot as plt

In [13]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [14]:
df.describe(include='object')

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Preferred Payment Method,Frequency of Purchases
count,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900
unique,2,25,4,50,4,25,4,2,6,6,2,2,6,7
top,Male,Blouse,Clothing,Montana,M,Olive,Spring,No,Credit Card,Free Shipping,No,No,PayPal,Every 3 Months
freq,2652,171,1737,96,1755,177,999,2847,696,675,2223,2223,677,584

In [23]:
##تحليل الإنفاق حسب الاشتراك

df.groupby("Subscription Status").agg(
    Customers=("Customer ID", "count"),
    Total_Sales=("Purchase Amount (USD)", "sum"),
    Avg_Spending=("Purchase Amount (USD)", "mean")
).round(2)

                     Customers  Total_Sales  Avg_Spending
Subscription Status
No                        2847       170436         59.87
Yes                       1053        62645         59.49

In [25]:
###تأثير الخصومات على الإنفاق
df.groupby("Discount Applied").agg(
    Customers=("Customer ID", "count"),
    Total_Sales=("Purchase Amount (USD)", "sum"),
    Avg_Spending=("Purchase Amount (USD)", "mean")
).round(2)

                  Customers  Total_Sales  Avg_Spending
Discount Applied
No                     2223       133670         60.13
Yes                    1677        99411         59.28

In [27]:
###تحليل المبيعات حسب الموسم
df.groupby("Season").agg(
    Customers=("Customer ID", "count"),
    Total_Sales=("Purchase Amount (USD)", "sum"),
    Avg_Spending=("Purchase Amount (USD)", "mean")
).round(2).sort_values("Total_Sales",ascending=False)

        Customers  Total_Sales  Avg_Spending
Season
Fall          975        60018         61.56
Spring        999        58679         58.74
Winter        971        58607         60.36
Summer        955        55777         58.41

In [29]:
###تحليل طرق الدفع
df.groupby("Payment Method").agg(
    Customers=("Customer ID", "count"),
    Total_Sales=("Purchase Amount (USD)", "sum"),
    Avg_Spending=("Purchase Amount (USD)", "mean")
).round(2).sort_values("Total_Sales",ascending=False)

                Customers  Total_Sales  Avg_Spending
Payment Method
Credit Card           696        42567         61.16
Venmo                 653        39991         61.24
Cash                  648        38833         59.93
PayPal                638        37449         58.70
Bank Transfer         632        37123         58.74
Debit Card            633        37118         58.64

In [30]:
###تحليل المبيعات حسب النوع
df.groupby("Gender").agg(
    Customers=("Customer ID", "count"),
    Total_Sales=("Purchase Amount (USD)", "sum"),
    Avg_Spending=("Purchase Amount (USD)", "mean")
).round(2).sort_values("Total_Sales",ascending=False)

        Customers  Total_Sales  Avg_Spending
Gender
Male         2652       157890         59.54
Female       1248        75191         60.25

In [31]:
##أعلى 10 منتجات حسب إجمالي المبيعات.

df.groupby("Item Purchased")["Purchase Amount (USD)"].sum().sort_values(ascending=False).head(10)

Item Purchased
Blouse        10410
Shirt         10332
Dress         10320
Pants         10090
Jewelry       10010
Sunglasses     9649
Belt           9635
Scarf          9561
Sweater        9462
Shorts         9433
Name: Purchase Amount (USD), dtype: int64

In [32]:
###تحليل تقييمات العملاء حسب الفئة

df.groupby("Category")["Review Rating"].mean().sort_values(ascending=False).round(2)

Category
Footwear       3.79
Accessories    3.77
Outerwear      3.75
Clothing       3.72
Name: Review Rating, dtype: float64

In [33]:
###تحليل تكرار الشراء

df.groupby("Frequency of Purchases").agg(
    Customers=("Customer ID", "count"),
    Avg_Spending=("Purchase Amount (USD)", "mean")
).round(2).sort_values("Customers", ascending=False)

                        Customers  Avg_Spending
Frequency of Purchases
Every 3 Months                584         60.08
Annually                      572         60.17
Quarterly                     563         59.98
Monthly                       553         59.33
Bi-Weekly                     547         60.69
Fortnightly                   542         59.05
Weekly                        539         58.97

In [35]:
print(df.dtypes)
print("Unique Customer IDs:", df["Customer ID"].nunique())
print("Total Rows:", len(df))

Customer ID                   int64
Age                           int64
Gender                       object
Item Purchased               object
Category                     object
Purchase Amount (USD)         int64
Location                     object
Size                         object
Color                        object
Season                       object
Review Rating               float64
Subscription Status          object
Payment Method               object
Shipping Type                object
Discount Applied             object
Promo Code Used              object
Previous Purchases            int64
Preferred Payment Method     object
Frequency of Purchases       object
dtype: object
Unique Customer IDs: 3900
Total Rows: 3900

In [24]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Payment Method',
       'Shipping Type', 'Discount Applied', 'Promo Code Used',
       'Previous Purchases', 'Preferred Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [36]:
df.to_csv('cleaned_Customer_Shopping.csv',index=False)
files.download('cleaned_Customer_Shopping.csv')